# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'comment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomment.proto\x12\x06rpcapi\",\n\nRawComment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nrawComment\x18\x02 \x01(\t\"g\n\x11\x43lassifiedComment\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x16\n\x0esimilarComment\x18\x04 \x03(\t\x12\x10\n\x08keywords\x18\x05 \x03(\t\"3\n\x0bRawComments\x12$\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x12.rpcapi.RawComment\"A\n\x12\x43lassifiedComments\x12+\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x19.rpcapi.ClassifiedComment2Z\n\x11\x43ommentClassifier\x12\x45\n\x10\x43lassifyComments\x12\x13.rpcapi.RawComments\x1a\x1a.rpcapi.ClassifiedComments0\x01\x42\x11Z\x0finternal/rpcapib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017internal/rpcapi'
  _globals['_RAWCOMMENT']._serialized_start=25
  _globals['_RAWCOMMENT']._serialized_end=69
  _globals['_CLASSIFIEDCOMMENT']._serialized_start=71
  _globals['_CLASSIFIEDCOMMENT']._serialized_end=174
  _globals['_RAWCOMMENTS']._serialized_start=176
  _globals['_RAWCOMMENTS']._serialized_end=227
  _globals['_CLASSIFIEDCOMMENTS']._serialized_start=229
  _globals['_CLASSIFIEDCOMMENTS']._serialized_end=294
  _globals['_COMMENTCLASSIFIER']._serialized_start=296
  _globals['_COMMENTCLASSIFIER']._serialized_end=386
# @@protoc_insertion_point(module_scope)
