package data

import "go.mongodb.org/mongo-driver/bson/primitive"

// Category is the category generated by LLM
type Category struct {
	ID   primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`
	Name string             `bson:"name" json:"name"`
}
