package controllers

import (
	"CommentClassifier/internal/data"
	"CommentClassifier/internal/db"
	"CommentClassifier/internal/utils"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"net/http"
)

// GetComments returns all comments and implements paging functions
func GetComments(c *gin.Context) {
	var request utils.GetCommentsRequest
	if err := c.ShouldBind(&request); err != nil {
		c.JSON(http.StatusBadRequest,
			utils.NewErrorResponse(http.StatusBadRequest, "Invalid request payload"))
		return
	}

	// Set default values if necessary
	if request.Page < 1 {
		request.Page = 1
	}
	if request.Limit < 1 {
		request.Limit = 10
	}
	skip := (request.Page - 1) * request.Limit

	// Count matching comments by categories
	totalComments, err := db.CountComments(c, request.Categories)
	if err != nil {
		c.JSON(http.StatusInternalServerError,
			utils.NewErrorResponse(http.StatusInternalServerError, "Failed to count comments: "+err.Error()))
		return
	}

	// Calculate total pages
	totalPages := (totalComments + request.Limit - 1) / request.Limit

	// Find matching comments
	comments, err := db.FindComments(c, skip, request.Limit, request.Categories)
	if err != nil {
		c.JSON(http.StatusInternalServerError,
			utils.NewErrorResponse(http.StatusInternalServerError, "Failed to find comments: "+err.Error()))
		return
	}

	// Avoid front-end crash
	if comments == nil {
		comments = make([]data.Comment, 0)
	}

	c.JSON(http.StatusOK,
		utils.NewSuccessResponse(http.StatusOK, utils.GetCommentsResponse{
			Page:          request.Page,
			Limit:         request.Limit,
			TotalPages:    totalPages,
			TotalComments: totalComments,
			Comments:      comments,
		}))
	return
}

// OverwriteCategory overwrites a category generated by AI or created by another user
func OverwriteCategory(c *gin.Context) {
	var request utils.OverwriteCategoryRequest
	if err := c.ShouldBind(&request); err != nil {
		c.JSON(http.StatusBadRequest,
			utils.NewErrorResponse(http.StatusBadRequest, "Invalid request payload"))
		return
	}

	id, err := primitive.ObjectIDFromHex(request.ID)
	if err != nil {
		c.JSON(http.StatusBadRequest,
			utils.NewErrorResponse(http.StatusBadRequest, "Invalid ObjectID"))
		return
	}

	// Get user from context
	username, err := GetUserFromContext(c)
	if err != nil {
		c.JSON(http.StatusUnauthorized,
			utils.NewErrorResponse(http.StatusUnauthorized, "Unauthorized"))
	}

	// Add modification history
	if err := db.UpdateCommentCategory(c, id, request.Category, username, request.Comment); err != nil {
		c.JSON(http.StatusInternalServerError,
			utils.NewErrorResponse(http.StatusInternalServerError, "Failed to update comment category: "+err.Error()))
		return
	}

	// Add category if required
	if err := db.AddCategory(c, request.Category); err != nil {
		c.JSON(http.StatusInternalServerError,
			utils.NewErrorResponse(http.StatusInternalServerError, "Failed to update comment category: "+err.Error()))
		return
	}

	c.JSON(http.StatusCreated, utils.NewSuccessResponse(http.StatusCreated, ""))
	return
}
