// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: comment.proto

package rpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommentClassifier_ClassifyComments_FullMethodName = "/rpcapi.CommentClassifier/ClassifyComments"
)

// CommentClassifierClient is the client API for CommentClassifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClassifierClient interface {
	// ClassifyComments takes array of RawComment as input, and provide multiple arrays of ClassifiedComments as output
	ClassifyComments(ctx context.Context, in *RawComments, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClassifiedComments], error)
}

type commentClassifierClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClassifierClient(cc grpc.ClientConnInterface) CommentClassifierClient {
	return &commentClassifierClient{cc}
}

func (c *commentClassifierClient) ClassifyComments(ctx context.Context, in *RawComments, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClassifiedComments], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommentClassifier_ServiceDesc.Streams[0], CommentClassifier_ClassifyComments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawComments, ClassifiedComments]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommentClassifier_ClassifyCommentsClient = grpc.ServerStreamingClient[ClassifiedComments]

// CommentClassifierServer is the server API for CommentClassifier service.
// All implementations must embed UnimplementedCommentClassifierServer
// for forward compatibility.
type CommentClassifierServer interface {
	// ClassifyComments takes array of RawComment as input, and provide multiple arrays of ClassifiedComments as output
	ClassifyComments(*RawComments, grpc.ServerStreamingServer[ClassifiedComments]) error
	mustEmbedUnimplementedCommentClassifierServer()
}

// UnimplementedCommentClassifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommentClassifierServer struct{}

func (UnimplementedCommentClassifierServer) ClassifyComments(*RawComments, grpc.ServerStreamingServer[ClassifiedComments]) error {
	return status.Errorf(codes.Unimplemented, "method ClassifyComments not implemented")
}
func (UnimplementedCommentClassifierServer) mustEmbedUnimplementedCommentClassifierServer() {}
func (UnimplementedCommentClassifierServer) testEmbeddedByValue()                           {}

// UnsafeCommentClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentClassifierServer will
// result in compilation errors.
type UnsafeCommentClassifierServer interface {
	mustEmbedUnimplementedCommentClassifierServer()
}

func RegisterCommentClassifierServer(s grpc.ServiceRegistrar, srv CommentClassifierServer) {
	// If the following call pancis, it indicates UnimplementedCommentClassifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommentClassifier_ServiceDesc, srv)
}

func _CommentClassifier_ClassifyComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RawComments)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommentClassifierServer).ClassifyComments(m, &grpc.GenericServerStream[RawComments, ClassifiedComments]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommentClassifier_ClassifyCommentsServer = grpc.ServerStreamingServer[ClassifiedComments]

// CommentClassifier_ServiceDesc is the grpc.ServiceDesc for CommentClassifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentClassifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcapi.CommentClassifier",
	HandlerType: (*CommentClassifierServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClassifyComments",
			Handler:       _CommentClassifier_ClassifyComments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "comment.proto",
}
