// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: comment.proto

package rpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawComment is the original comments information required by AI module for classification
type RawComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                 // MongoDB ObjectID
	RawComment    string                 `protobuf:"bytes,2,opt,name=rawComment,proto3" json:"rawComment,omitempty"` // Comment content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawComment) Reset() {
	*x = RawComment{}
	mi := &file_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawComment) ProtoMessage() {}

func (x *RawComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawComment.ProtoReflect.Descriptor instead.
func (*RawComment) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

func (x *RawComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawComment) GetRawComment() string {
	if x != nil {
		return x.RawComment
	}
	return ""
}

// ClassifiedComment is the classified comments with category and confidence score provided by AI module
type ClassifiedComment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                         // MongoDB ObjectID
	Label          string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                   // AI-generated category
	Score          float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`                 // Confidence score
	SimilarComment []string               `protobuf:"bytes,4,rep,name=similarComment,proto3" json:"similarComment,omitempty"` // Array of content of similar comments
	Keywords       []string               `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClassifiedComment) Reset() {
	*x = ClassifiedComment{}
	mi := &file_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifiedComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedComment) ProtoMessage() {}

func (x *ClassifiedComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedComment.ProtoReflect.Descriptor instead.
func (*ClassifiedComment) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifiedComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassifiedComment) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ClassifiedComment) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ClassifiedComment) GetSimilarComment() []string {
	if x != nil {
		return x.SimilarComment
	}
	return nil
}

func (x *ClassifiedComment) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// RawComments is array of original comments information
type RawComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*RawComment          `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawComments) Reset() {
	*x = RawComments{}
	mi := &file_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawComments) ProtoMessage() {}

func (x *RawComments) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawComments.ProtoReflect.Descriptor instead.
func (*RawComments) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{2}
}

func (x *RawComments) GetComments() []*RawComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// ClassifiedComments is array of classified comments
type ClassifiedComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*ClassifiedComment   `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifiedComments) Reset() {
	*x = ClassifiedComments{}
	mi := &file_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifiedComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedComments) ProtoMessage() {}

func (x *ClassifiedComments) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedComments.ProtoReflect.Descriptor instead.
func (*ClassifiedComments) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifiedComments) GetComments() []*ClassifiedComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_comment_proto protoreflect.FileDescriptor

const file_comment_proto_rawDesc = "" +
	"\n" +
	"\rcomment.proto\x12\x06rpcapi\"<\n" +
	"\n" +
	"RawComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"rawComment\x18\x02 \x01(\tR\n" +
	"rawComment\"\x93\x01\n" +
	"\x11ClassifiedComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12&\n" +
	"\x0esimilarComment\x18\x04 \x03(\tR\x0esimilarComment\x12\x1a\n" +
	"\bkeywords\x18\x05 \x03(\tR\bkeywords\"=\n" +
	"\vRawComments\x12.\n" +
	"\bcomments\x18\x01 \x03(\v2\x12.rpcapi.RawCommentR\bcomments\"K\n" +
	"\x12ClassifiedComments\x125\n" +
	"\bcomments\x18\x01 \x03(\v2\x19.rpcapi.ClassifiedCommentR\bcomments2Z\n" +
	"\x11CommentClassifier\x12E\n" +
	"\x10ClassifyComments\x12\x13.rpcapi.RawComments\x1a\x1a.rpcapi.ClassifiedComments0\x01B\x11Z\x0finternal/rpcapib\x06proto3"

var (
	file_comment_proto_rawDescOnce sync.Once
	file_comment_proto_rawDescData []byte
)

func file_comment_proto_rawDescGZIP() []byte {
	file_comment_proto_rawDescOnce.Do(func() {
		file_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)))
	})
	return file_comment_proto_rawDescData
}

var file_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_comment_proto_goTypes = []any{
	(*RawComment)(nil),         // 0: rpcapi.RawComment
	(*ClassifiedComment)(nil),  // 1: rpcapi.ClassifiedComment
	(*RawComments)(nil),        // 2: rpcapi.RawComments
	(*ClassifiedComments)(nil), // 3: rpcapi.ClassifiedComments
}
var file_comment_proto_depIdxs = []int32{
	0, // 0: rpcapi.RawComments.comments:type_name -> rpcapi.RawComment
	1, // 1: rpcapi.ClassifiedComments.comments:type_name -> rpcapi.ClassifiedComment
	2, // 2: rpcapi.CommentClassifier.ClassifyComments:input_type -> rpcapi.RawComments
	3, // 3: rpcapi.CommentClassifier.ClassifyComments:output_type -> rpcapi.ClassifiedComments
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comment_proto_init() }
func file_comment_proto_init() {
	if File_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_proto_goTypes,
		DependencyIndexes: file_comment_proto_depIdxs,
		MessageInfos:      file_comment_proto_msgTypes,
	}.Build()
	File_comment_proto = out.File
	file_comment_proto_goTypes = nil
	file_comment_proto_depIdxs = nil
}
